# code: language=ansible
---
- name: Get MySQL version.
  ansible.builtin.command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false
  check_mode: false

- ansible.builtin.debug:
    var: mysql_cli_version

- name: Configure MySQL server.
  become: true
  community.general.ini_file:
    dest: "{{ mysql_configuration_destination }}/{{ mysql_name }}-server.cnf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: "0644"
  loop: "{{ mysql_configuration_options }}"
  loop_control:
    label: "{{ item.option }}"
  notify:
    - Restart MySQL server

- name: Configure MySQL client.
  become: true
  community.general.ini_file:
    dest: "{{ mysql_configuration_destination }}/{{ mysql_name }}-client.cnf"
    section: client
    option: socket
    value: "{{ mysql_socket }}"
    mode: "0644"

- name: Start and enable MySQL
  become: true
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: started
    enabled: true
