---
# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-ArchLinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  ansible.builtin.set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

- name: configure mysql
  include_tasks: configure.yml

- name: run mysql security
  include_tasks: secure-installation.yml

- name: create databases
  include_tasks: databases.yml

- name: create users
  include_tasks: users.yml

- name: flush handlers again
  ansible.builtin.meta: flush_handlers
