# code: language=ansible
---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ lookup('first_found', mysql_variables) }}"

- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: setup-ArchLinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  ansible.builtin.set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

- name: Configure mysql
  ansible.builtin.include_tasks: configure.yml

- name: Run mysql security
  ansible.builtin.include_tasks: secure-installation.yml

- name: Create databases
  ansible.builtin.include_tasks: databases.yml

- name: Create users
  ansible.builtin.include_tasks: users.yml
