---
- name: Install MySQL package
  become: true
  ansible.builtin.package:
    name: "{{ mysql_packages }}"
    state: present
  register: arch_mysql_install_packages

- name: initialize mysql
  become: true
  ansible.builtin.command:
    cmd: "{{ mysql_initialize_command }}"
    creates: /var/lib/mysql/mysql
  when:
    - arch_mysql_install_packages.changed
