---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  register: _pre_update_apt_cache
  until: _pre_update_apt_cache is succeeded
  when:
    - ansible_pkg_mgr == "apt"

- name: Install MySQL package
  become: true
  ansible.builtin.package:
    name: "{{ mysql_packages }}"
    state: present
  register: deb_mysql_install_packages

- name: Stop MySQL if started automatically
  become: true
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: stopped
  when: deb_mysql_install_packages.changed
