# code: language=ansible
---
# handlers file for mysql

- name: Systemctl reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: Restart MySQL server
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool
    - ansible_service_mgr == "systemd"
